name: Claude Requirements Pilot

on:
  issue_comment:
    types: [created]

jobs:
  requirements-pilot:
    if: contains(github.event.comment.body, '@claude') && contains(github.event.comment.body, '/requirements-pilot')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Requirements Pilot
        id: requirements-pilot
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_env: |
            ANTHROPIC_BASE_URL: https://co.yes.vg
          direct_prompt: |
            You are executing the /requirements-pilot command. 
            
            User request: ${{ github.event.comment.body }}
            
            Please:
            1. Extract the feature description from the comment (after /requirements-pilot)
            2. Read the .claude/commands/requirements-pilot.md file for detailed instructions
            3. Execute PHASE 1 ONLY: Requirements confirmation process
            4. Follow the 100-point quality assessment system
            5. Create the .claude/specs/{feature-name}/ directory structure
            6. Save confirmation to requirements-confirm.md
            7. After reaching 90+ quality score, ask user to comment "@claude proceed"
            
            **IMPORTANT**: Do NOT execute the sub-agent chain automatically. Only do requirements confirmation.

  # Handle user approval for implementation
  execute-implementation:
    if: |
      contains(github.event.comment.body, '@claude') && 
      (contains(github.event.comment.body, 'proceed') || 
       contains(github.event.comment.body, 'approve'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Execute Implementation Chain
        id: implementation
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_env: |
            ANTHROPIC_BASE_URL: https://co.yes.vg
          direct_prompt: |
            User has approved proceeding with implementation.
            
            Please:
            1. Find the latest requirements-confirm.md file in .claude/specs/
            2. Execute the complete agent chain as specified in requirements-pilot.md:
               - requirements-generate: Create technical specifications
               - requirements-code: Implement functionality
               - requirements-review: Evaluate quality (90% threshold)
               - requirements-testing: Create test suite
            3. Use quality gates and iteration loops as needed
            4. Provide final implementation summary
            
            Begin the implementation phase now.